env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  complexity:
    - error
    - 10
  curly:
    - error
    - all
  max-depth: error
  max-params: error
